### ISSUE TITLE
Implement "shortcut maps" feature

### ISSUE THREAD

**Issue by bpstahlman** [bpstahlman/txtfmt#11]
See issue #9 for motivation behind this. Need to flesh out the details a bit more, but I'm thinking something along the following lines (syntax still rough and conceptual)...

```
let txtfmtShortcuts = [
        'vo \rb cr,f=b',
        'vo \yu cy,f+u'
]
```

**Explanation:** Would define both visual and operator-pending maps for \rb and \yu (4 maps in all):
- `\rb` - Make the visually-selected or operated-on text red-bold.
- `\yu` - Color yellow and underline the visually-selected or operated-on text.

**Notes:**
- The shortcut maps would work just like `\h`, but with the highlighting spec hardcoded to obviate the need for a user prompt.
- The 'vo' flags at the head of the definition cause the shortcuts to be available as both visual and operator-pending maps.
  **TODO:** Evaluate utility of this: is there a significant advantage to allowing different permutations of 'v' and 'o', or should we unconditionally define both? Note that with the syntax shown above, at least one flag would be mandatory.
- Any highlighting spec that would be legal at a Txtfmt prompt would be permissible here: e.g., a _selector pattern expression_ could be used to target only specific portions of the visually-selected or operated-on text.
- Since the shortcuts are just regular maps, there's no reason they couldn't be used within a "user map" sequence.

**TODO:** Consider whether the "clear all" functionality suggested by @pdoak (issue #8) should be implemented in terms of the shortcut mechanism.

**Comment by pdoak** [comment]
@bpstahlman : these sound like really useful shortcuts. Would you also allow the user to create their own shortcuts?

**Comment by bpstahlman** [comment]
@pdoak: Yes. The `\rb` and `\yu` maps were simply examples to illustrate one possible syntax. The user would be responsible for the contents of the `txtfmtShortcuts` array, and could add as many or as few shortcuts as he liked. It would probably work like the `txtfmtUsermap` array, which can be set globally (e.g., in a vimrc) or buf-locally (e.g., in an autocommand for specific file types).

If the user didn't set `txtfmtShorcuts`, no shortcuts would be created - unless I decided to predefine a few obvious defaults: e.g., a map to clear highlights, maps for bold, underline, italic (e.g., \b, \u, \i), etc...

**Comment by benintech** [comment]
+1

**Comment by benintech** [comment]
+1 here
Could be useful for example to format some code in a txt file.
Being able to select some text, and then just do for example \c (c for code) to format it to a self defined format (for example black on turquoise background) would definitely be great

**Comment by bpstahlman** [comment]
@benintech Agreed. Actually, if you commented out the inputsave() / inputrestore() calls in Prompt_fmt_clr_spec() (in ftplugin/txtfmt.vim), you could set up simple mappings for that sort of thing now. For example, the following mapping would make the highlighted text red bold:
`xmap <Bslash>c :<C-w>exe "normal gv\<lt>bslash>hfb,kr\<lt>cr>"<cr>`

But the proposed feature will make it much cleaner/simpler. This feature and one permitting arbitrarily-colored undercurl are near the top of the TODO list. But first I need to release an updated syntax engine, which greatly speeds up highlighting in a number of scenarios. It's mostly done, but I have some final touches and testing to complete...

**Comment by bpstahlman** [comment]
**Update:** Finally released the updated syntax engine. I also have a working prototype of the colored undercurl feature, but I'm planning to implement and release the auto maps feature first because I suspect it has greater utility to the greater number of users...

**Comment by bpstahlman** [comment]
@benintech @pdoak @pascualpobil
Development of this feature is mostly complete on [the shortcut-maps branch](https://github.com/bpstahlman/txtfmt/tree/shortcut-maps).

The feature is documented in [a new section](https://github.com/bpstahlman/txtfmt/blob/shortcut-maps/README.md#shortcut-maps) of the README.

Feedback and suggestions are welcome from anyone who has a chance to try out the branch. I plan to do a bit more cleanup before merging to master but will attempt to keep the branch in a state that makes it a suitable target for a plugin manager.

One enhancement I'm still considering is a way to specify on a shortcut-by-shortcut basis (as opposed to globally via option `txtfmtShortcutsStayInVisual`) whether the visual selection remains active after a highlighting operation. The motivation for this is that shortcuts that accomplish very limited highlighting changes (e.g., adding a single formatting attribute such as bold or italic) are more likely to be applied in "batches", and hence, more likely to benefit from the "stay in visual" behavior. On the other hand, a more complex mapping (e.g., add bold, italic, red foreground, green background) is more likely to be applied as a standalone operation, in which case, the "stay in visual" behavior could be a source of annoyance, as it would require the user to hit `<Esc>` to make the highlighting changes fully visible.

**Comment by bpstahlman** [comment]
@benintech @pdoak @pascualpobil
The shortcut-maps feature has been merged to master.
I plan to upload it to the Vim scripts site as v5.0.
