### ISSUE TITLE
A couple of improvement ideas.

### ISSUE THREAD

**Issue by ubaldot** [bpstahlman/txtfmt#25]
I am just trying out this plugin and it looks nice!
However, I have a couple of issues which I don't know are already handled and I just cannot find how to, or could be ideas for improvements :)

1. The `ft` must be `txtfmt`, but then all the syntax highlight of the original file is lost. For example, I have a nice syntax highlight for my `.vimrc` but when I change ft then all the syntax highlight has gone. Furthermore, change of ft may interfere with other plugin. For example, in the case of _vim-commentary,_ when adding a comment in `ft=vim` files I correctly have `#` (I am using Vim9), whereas when I change it to `ft=txtfmt` I have `/* ... */ `. 

2. Perhaps at the very beginning of the docs it shall be stand out that the ft must be changed.

**Comment by bpstahlman** [comment]
> I am just trying out this plugin and it looks nice! However, I have a couple of issues which I don't know are already handled and I just cannot find how to, or could be ideas for improvements :)

@ubaldot Thanks! Suggestions for improvement are always welcome.

> 
> 1. The `ft` must be `txtfmt`, but then all the syntax highlight of the original file is lost. For example, I have a nice syntax highlight for my `.vimrc` but when I change ft then all the syntax highlight has gone. Furthermore, change of ft may interfere with other plugin. For example, in the case of _vim-commentary,_ when adding a comment in `ft=vim` files I correctly have `#` (I am using Vim9), whereas when I change it to `ft=txtfmt` I have `/* ... */ `.

It is indeed possible to use Txtfmt in conjunction with other filetype plugins, and even to nest Txtfmt highlighting regions within non-Txtfmt regions. For details...

:help txtfmt-combining
:help txtfmt-nesting

> 2. Perhaps at the very beginning of the docs it shall be stand out that the ft must be changed.

Which docs are you referring to? I expect most users to start with the README, which shows the use of `:set ft=txtfmt` in the first section. Are you perhaps referring to the builtin plugin help file? The builtin help is far more detailed than the README, but not as up to date. I've added significant functionality that's documented only in the README.

**Comment by ubaldot** [comment]
> It is indeed possible to use Txtfmt in conjunction with other filetype plugins, and even to nest Txtfmt highlighting regions within non-Txtfmt regions. For details...
> 
> :help txtfmt-combining
> :help txtfmt-nesting

This solve my problem. Thanks!

> Which docs are you referring to? I expect most users to start with the README, which shows the use of :set ft=txtfmt in the first section. Are you perhaps referring to the builtin plugin help file? The builtin help is far more detailed than the README, but not as up to date. I've added significant functionality that's documented only in the README.

I am actually referring to the README but.... my bad.
I jumped directly to the `[example](https://github.com/bpstahlman/txtfmt#operator-auto-maps)` and I cannot make my `\h` to work. This because `ft` was not `txtfmt`.  Now it is solved though. 

I have another, unrelated, question - but it seems an easy fix so I won't open another issue. 
Adding the following line

`g:txtfmtColor{2}='^R$,c:LightRed,g:#fbe3da'`

in my .vimrc result is **E1241: Separator not supported** error.

How to fix it?

**Comment by bpstahlman** [comment]
> 
> I have another, unrelated, question - but it seems an easy fix so I won't open another issue. Adding the following line
> 
> `g:txtfmtColor{2}='^R$,c:LightRed,g:#fbe3da'`
> 
> in my .vimrc result is **E1241: Separator not supported** error.
> 
> How to fix it?

The variable assignment is missing a `let`. Try this...
```
let g:txtfmtColor{2}='^R$,c:LightRed,g:#fbe3da'
```

**Comment by ubaldot** [comment]
Forgot to mention that I am using Vim9. 
I cannot use let to define global variables.

**Comment by bpstahlman** [comment]
> 

Ah. Vim9 apparently doesn't support curly brace syntax. Also, it requires whitespace before and after the `=`. Try this...
```
g:txtfmtColor2 = '^R$,c:LightRed,g:#fbe3da'
```
Note: The curly braces aren't really necessary; they just make the variable access look more like an array access.

**Comment by bpstahlman** [comment]
Sorry. Just realized I accidentally closed this issue. (Actually, I think my cat did.) Anyways, let me know if that fixes it for you...

**Comment by ubaldot** [comment]
Your cat was right. The problem has been solved. Thanks! :)
