### ISSUE TITLE
I don't know if it is a real bug, but when I change background the highlight is lost.

### ISSUE THREAD

**Issue by ubaldot** [bpstahlman/txtfmt#26]
I notice that when I change the `background` from `light` to `dark`, the highlight is lost. And when I change back to `light` is also lost. I have to `:e!` get the highlight back.

I am not sure if it is a bug. 
I have the following my `.vimrc`:

```
g:txtfmtBgcolor2 = '^R$,c:LightRed,g:' .. matchstr(execute('highlight DiffDelete'), 'guibg=\zs#\x\+')
g:txtfmtBgcolor3 = '^Y$,c:LightYellow,g:' .. matchstr(execute('highlight DiffChange'), 'guibg=\zs#\x\+')
g:txtfmtBgcolor5 = '^G$,c:LightGreen,g:' .. matchstr(execute('highlight DiffAdd'), 'guibg=\zs#\x\+')

g:txtfmtShortcuts = []

# Note: Shortcuts that don't specify modes will get select mode mappings if and only if txtfmtShortcutsWorkInSelect=1.
# bold-underline (\u for Visual and Operator)
add(g:txtfmtShortcuts, 'h1 kR')
add(g:txtfmtShortcuts, 'h2 kY')
add(g:txtfmtShortcuts, 'h3 kG')
add(g:txtfmtShortcuts, 'hh k-')
```

and I am using `MacVim 9.0.1897` and `everforest` color scheme.

**Comment by bpstahlman** [comment]
I'll attempt to reproduce this weekend.

Have you tried using the :Refresh command after you change background?

Thanks, Brett S.

**Comment by ubaldot** [comment]
The problem is on my side: Vim load the .vimrc only once. If I change the background color while working, then the highlight groups also change but the variables `g:txtfmtBgcolor2` are assigned as they have been assigned at Vim startup, when the .vimrc file is executed.
